<?php

# load database model and helper classes
module_load_include('php', 'itonics_employee', 'itonics_employee_model');
module_load_include('php', 'itonics_employee', 'itonics_employee_helper');

/**
* Implements hook_menu
* @see https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_menu/7.x
* @uses Itonics_Employee_Helper::menu()
* @param void
* @return array
*/
function itonics_employee_menu(){
	$items[Itonics_Employee_Helper::menu('list')] = array(
		'title'            => 'Itonics Employees',
		'description'      => 'Records for itonics employees',
	    'page callback'    => 'drupal_get_form',
	    'page arguments'   => array('itonics_employee_list_form'),
	    'access arguments' => array('administer itonics employee'),
	    'file'             => 'itonics_employee_list.inc'
	);

	$items[Itonics_Employee_Helper::menu('add')] = array(
		'title'            => 'Add Employees',
		'description'      => 'Add employees',
	    'page callback'    => 'drupal_get_form',
	    'page arguments'   => array('itonics_employee_add_edit_form'),
	    'access arguments' => array('administer itonics employee'),
	    'file'             => 'itonics_employee_add_edit.inc'
	);

	$items[Itonics_Employee_Helper::menu('edit')] = array(
		'title'            => 'Edit Employee',
		'description'      => 'Edit employee',
	    'page callback'    => 'itonics_employee_edit',
	    'access arguments' => array('administer itonics employee'),
	    'file'             => 'itonics_employee_add_edit.inc'
	);
	
	return $items;
}

/**
* Implements hook_permission
* @see https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_permission/7.x
* @param void
* @return array
*/
function itonics_employee_permission(){
	return array(
		'administer itonics employee' => array(
			'title' => t('Administer Itonics Employees'),
		)
	);
}

/**
* Returns an array of address
* @param void
* @return array
*/
function itonics_employee_get_address(){
	return array(
       'nepal' => t('Nepal'),
       'india' => t('India'),
       'china' => t('China'),
    );
}

/**
* Returns an array of gender
* @param void
* @return array
*/
function itonics_employee_get_gender(){
	return array(
		'male'   => t('Male'), 
		'female' => t('Female'), 
		'other'  => t('Other')
	);
}

